application-description: REST API to manage Github repositories
application-title: TUI Homework API
application-version: 0.0.1
error:
  message:
    notAcceptable: Not acceptable request
    notFound: Github user not found
github:
    url: https://api.github.com
    header: Link
    params:
      perPage: 100
springdoc:
  api-docs:
    path: /api-docs